apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user-api-deployment
  labels:
    app: backend-user-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user-api
  template:
    metadata:
      labels:
        app: backend-user-api
    spec:
      containers:
        - name: backend-user-api
          image: demarauder/udagram-api-user:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: udagram-config
            - secretRef:
                name: aws-secret
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            
